/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../../app/ui/noty/noty';
const styles_NotyComponent:any[] = ['.noty[_ngcontent-%COMP%] {\n      position: fixed;\n      left: 50%;\n      bottom: 0;\n      transform: translateX(-50%);\n      min-width: 288px;\n      max-width: 568px;\n      padding: 14px 24px;\n      background: #323232;\n      border-radius: 2px;\n      color: #fff;\n    }\n    .noty.error[_ngcontent-%COMP%] {\n      background: #990000;\n    }'];
export const RenderType_NotyComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_NotyComponent,data:{'animation':[{type:7,name:'appearNoty',definitions:[{type:1,
        expr:':enter',animation:[{type:6,styles:{transform:'translate(-50%, 100%)',
            color:'transparent'},offset:(null as any)},{type:3,steps:[{type:4,styles:{type:6,
            styles:{transform:'translate(-50%, 0)',easing:'cubic-bezier(0.0, 0.0, 0.2, 1)'},
            offset:(null as any)},timings:'275ms'},{type:4,styles:{type:6,styles:{color:'#fff'},
            offset:(null as any)},timings:'275ms 100ms ease'}],options:(null as any)}],
        options:(null as any)},{type:1,expr:'* => destroyed',animation:[{type:4,styles:{type:6,
        styles:{transform:'translate(-50%, 100%)',easing:'cubic-bezier(0.4, 0.0, 1, 1)'},
        offset:(null as any)},timings:'250ms'}],options:(null as any)}],options:{}}]}});
export function View_NotyComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',[['class','noty']],[[24,'@appearNoty',0],[2,'error',(null as any)]],
      [[(null as any),'@appearNoty.done'],[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.NotyComponent = _v.component;
        if (('@appearNoty.done' === en)) {
          const pd_0:any = ((<any>_co.onAnimationDone($event)) !== false);
          ad = (pd_0 && ad);
        }
        if (('click' === en)) {
          const pd_1:any = ((<any>(_co.animationState = 'destroyed')) !== false);
          ad = (pd_1 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n      ','\n    '])),
      (_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(_ck,_v) => {
    var _co:i1.NotyComponent = _v.component;
    const currVal_0:any = _co.animationState;
    const currVal_1:any = _co.isError;
    _ck(_v,1,0,currVal_0,currVal_1);
    const currVal_2:any = _co.message;
    _ck(_v,2,0,currVal_2);
  });
}
export function View_NotyComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_NotyComponent_0,
      RenderType_NotyComponent)),i0.ɵdid(49152,(null as any),0,i1.NotyComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const NotyComponentNgFactory:i0.ComponentFactory<i1.NotyComponent> = i0.ɵccf('ng-component',
    i1.NotyComponent,View_NotyComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovT1NNUy9zcmMvbWFpbi9zcmMvYXBwL3VpL25vdHkvbm90eS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9PU01TL3NyYy9tYWluL3NyYy9hcHAvdWkvbm90eS9ub3R5LnRzIiwibmc6Ly8vRTovT1NNUy9zcmMvbWFpbi9zcmMvYXBwL3VpL25vdHkvbm90eS50cy5Ob3R5Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9FOi9PU01TL3NyYy9tYWluL3NyYy9hcHAvdWkvbm90eS9ub3R5LnRzLk5vdHlDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2IGNsYXNzPVwibm90eVwiXG4gICAgICBbQGFwcGVhck5vdHldPVwiYW5pbWF0aW9uU3RhdGVcIlxuICAgICAgKEBhcHBlYXJOb3R5LmRvbmUpPVwib25BbmltYXRpb25Eb25lKCRldmVudClcIlxuICAgICAgKGNsaWNrKT1cImFuaW1hdGlvblN0YXRlID0gJ2Rlc3Ryb3llZCdcIlxuICAgICAgW2NsYXNzLmVycm9yXT1cImlzRXJyb3JcIlxuICAgID5cbiAgICAgIHt7IG1lc3NhZ2UgfX1cbiAgICA8L2Rpdj5cbiAgIiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNJO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFFRTtVQUFBO1VBQUE7UUFBQTtRQUNBO1VBQUE7VUFBQTtRQUFBO1FBSEY7TUFBQSxnQ0FLQztNQUVLOztJQU5KO0lBR0E7SUFKRixXQUNFLFVBR0EsU0FKRjtJQUtDO0lBQUE7Ozs7b0JDTkw7TUFBQTs4QkFBQSxVQUFBO01BQUE7OzsifQ==
