/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.poshta-page[_ngcontent-%COMP%] {\n    min-height: calc(100vh - 48px);\n    background: #ededed;\n    padding: 30px 0 0;\n}\n\n.wrapper[_ngcontent-%COMP%] {\n    padding: 0;\n    background: #fff;\n    border-radius: 3px;\n    box-shadow: 0 1px 5px 0 rgba(0,0,0,0.4);\n}\n\n.tabs[_ngcontent-%COMP%] {\n    display: flex;\n    justify-content: center;\n    align-content: center;\n    height: 48px;\n    border-bottom: 1px solid #ededed;\n}\n\n.tab[_ngcontent-%COMP%] {\n    padding: 0 25px;\n    background: none;\n    border: none;\n    border-bottom: 1px solid transparent;\n    color: #000;\n    font: 500 13px/48px \'Roboto\';\n    text-transform: uppercase;\n    cursor: pointer;\n    transition: all .15s ease;\n}\n\n.tab[_ngcontent-%COMP%]:hover, .tab[_ngcontent-%COMP%]:active {\n    background: rgba(183, 183, 183, 0.1);\n    color: #338ea0;\n}\n\n.tab[_ngcontent-%COMP%]:focus {\n    outline: none;\n}\n\n.tab.active[_ngcontent-%COMP%] {\n    border-bottom-color: #42bcd4;\n    box-shadow: 0 1px 0 #42bcd4;\n    color: #42bcd4;\n}\n\n.tab-content[_ngcontent-%COMP%] {\n    padding: 30px 5%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWFsaWtvdi9JZGVhUHJvamVjdHMvb3Ntcy9zcmMvbWFpbi9zcmMvYXBwL2NvbnRhaW5lcnMvcG9zaHRhL3Bvc2h0YS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWFsaWtvdi9JZGVhUHJvamVjdHMvb3Ntcy9zcmMvbWFpbi9zcmMvYXBwL2NvbnRhaW5lcnMvcG9zaHRhL3Bvc2h0YS5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
