/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ui/header/header.ngfactory';
import * as i2 from '../../../../../app/ui/header/header';
import * as i3 from '@angular/router';
import * as i4 from '../../../../../app/services/popup.service';
import * as i5 from '../../../../../app/app';
import * as i6 from '../../../../../app/services/noty.service';
const styles_App:any[] = ([] as any[]);
export const RenderType_App:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_App,
    data:{}});
export function View_App_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'nav-header',([] as any[]),(null as any),(null as any),(null as any),
      i1.View_Header_0,i1.RenderType_Header)),i0.ɵdid(49152,(null as any),0,i2.Header,
      ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n  ']))],(_ck,_v) => {
    _ck(_v,5,0);
  },(null as any));
}
export function View_App_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(16777216,(null as any),(null as any),2,'app',([] as any[]),
      (null as any),(null as any),(null as any),View_App_0,RenderType_App)),i0.ɵprd(512,
      (null as any),i4.PopupService,i4.PopupService,[i0.ComponentFactoryResolver]),
      i0.ɵdid(114688,(null as any),0,i5.App,[i4.PopupService,i6.NotyService,i0.ViewContainerRef],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,2,0);
  },(null as any));
}
export const AppNgFactory:i0.ComponentFactory<i5.App> = i0.ɵccf('app',i5.App,View_App_Host_0,
    {},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovT1NNUy9zcmMvbWFpbi9zcmMvYXBwL2FwcC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9PU01TL3NyYy9tYWluL3NyYy9hcHAvYXBwLnRzIiwibmc6Ly8vRTovT1NNUy9zcmMvbWFpbi9zcmMvYXBwL2FwcC50cy5BcHAuaHRtbCIsIm5nOi8vL0U6L09TTVMvc3JjL21haW4vc3JjL2FwcC9hcHAudHMuQXBwX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPG5hdi1oZWFkZXI+PC9uYXYtaGVhZGVyPlxuICAgIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cbiAgIiwiPGFwcD48L2FwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNJO01BQUE7MkNBQUEsVUFBQTtNQUFBLDJDQUF5QjtNQUN6QjtVQUFBO2FBQUE7c0NBQUE7VUFBQSxlQUErQjtJQUEvQjs7OztvQkNGSjtNQUFBO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
