/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../app/boot';
import * as i2 from '../../../../../app/app';
import * as i3 from './containers/orders/orders.component.ngfactory';
import * as i4 from './containers/products/products.component.ngfactory';
import * as i5 from './containers/customers/customers.component.ngfactory';
import * as i6 from './ui/autocomplete-list/autocomplete-list.ngfactory';
import * as i7 from './ui/popup/popup.ngfactory';
import * as i8 from './ui/noty/noty.ngfactory';
import * as i9 from './app.ngfactory';
import * as i10 from '@angular/common';
import * as i11 from '@angular/platform-browser';
import * as i12 from '@angular/animations/browser';
import * as i13 from '@angular/platform-browser/animations';
import * as i14 from '@angular/animations';
import * as i15 from '@angular/http';
import * as i16 from '@angular/forms';
import * as i17 from '@angular/router';
import * as i18 from '../../../../../app/store';
import * as i19 from '../../../../../app/services/api.service';
import * as i20 from '../../../../../app/services/store-helper.service';
import * as i21 from '../../../../../app/services/search.service';
import * as i22 from '../../../../../app/services/customers.service';
import * as i23 from '../../../../../app/services/noty.service';
import * as i24 from '../../../../../app/services/orders.service';
import * as i25 from '../../../../../app/services/products.service';
import * as i26 from '../../../../../app/containers/orders/orders.component';
import * as i27 from '../../../../../app/containers/products/products.component';
import * as i28 from '../../../../../app/containers/customers/customers.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.App],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.OrdersComponentNgFactory,i4.ProductsComponentNgFactory,i5.CustomersComponentNgFactory,
              i6.AutocompleteListNgFactory,i7.PopupComponentNgFactory,i8.NotyComponentNgFactory,
              i9.AppNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4352,
          i0.LOCALE_ID,'ru-RU',([] as any[])),i0.ɵmpd(4608,i10.NgLocalization,i10.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i11.DomSanitizer,i11.ɵe,[i10.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i11.DomSanitizer]),i0.ɵmpd(4608,
              i11.HAMMER_GESTURE_CONFIG,i11.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i11.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i11.ɵDomEventsPlugin(p0_0),new i11.ɵKeyEventsPlugin(p1_0),
                    new i11.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i10.DOCUMENT,i10.DOCUMENT,i10.DOCUMENT,i11.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i11.EventManager,i11.EventManager,[i11.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i11.ɵDomSharedStylesHost,i11.ɵDomSharedStylesHost,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i11.ɵDomRendererFactory2,i11.ɵDomRendererFactory2,
              [i11.EventManager,i11.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i12.AnimationDriver,
              i13.ɵc,([] as any[])),i0.ɵmpd(5120,i12.ɵAnimationStyleNormalizer,i13.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i12.ɵAnimationEngine,i13.ɵb,[i12.AnimationDriver,
              i12.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i13.ɵe,
              [i11.ɵDomRendererFactory2,i12.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i11.ɵSharedStylesHost,(null as any),[i11.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i11.Meta,i11.Meta,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i11.Title,i11.Title,[i10.DOCUMENT]),i0.ɵmpd(4608,
              i14.AnimationBuilder,i13.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
                  i11.DOCUMENT]),i0.ɵmpd(4608,i15.BrowserXhr,i15.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i15.ResponseOptions,i15.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i15.XSRFStrategy,i15.ɵb,([] as any[])),i0.ɵmpd(4608,i15.XHRBackend,
              i15.XHRBackend,[i15.BrowserXhr,i15.ResponseOptions,i15.XSRFStrategy]),
          i0.ɵmpd(4608,i15.RequestOptions,i15.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i15.Http,i15.ɵc,[i15.XHRBackend,i15.RequestOptions]),i0.ɵmpd(4608,i16.ɵi,
              i16.ɵi,([] as any[])),i0.ɵmpd(4608,i16.FormBuilder,i16.FormBuilder,([] as any[])),
          i0.ɵmpd(5120,i17.ActivatedRoute,i17.ɵf,[i17.Router]),i0.ɵmpd(4608,i17.NoPreloading,
              i17.NoPreloading,([] as any[])),i0.ɵmpd(6144,i17.PreloadingStrategy,
              (null as any),[i17.NoPreloading]),i0.ɵmpd(135680,i17.RouterPreloader,
              i17.RouterPreloader,[i17.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i17.PreloadingStrategy]),i0.ɵmpd(4608,i17.PreloadAllModules,
              i17.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i17.ROUTER_INITIALIZER,
              i17.ɵi,[i17.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i17.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i18.Store,i18.Store,([] as any[])),
          i0.ɵmpd(4608,i19.ApiService,i19.ApiService,[i15.Http]),i0.ɵmpd(4608,i20.StoreHelper,
              i20.StoreHelper,[i18.Store]),i0.ɵmpd(4608,i21.SearchService,i21.SearchService,
              ([] as any[])),i0.ɵmpd(4608,i22.CustomerService,i22.CustomerService,
              [i19.ApiService,i20.StoreHelper,i21.SearchService]),i0.ɵmpd(4608,i23.NotyService,
              i23.NotyService,[i0.ComponentFactoryResolver]),i0.ɵmpd(4608,i24.OrderService,
              i24.OrderService,[i19.ApiService,i20.StoreHelper,i21.SearchService]),
          i0.ɵmpd(4608,i25.ProductService,i25.ProductService,[i19.ApiService,i20.StoreHelper,
              i21.SearchService]),i0.ɵmpd(512,i10.CommonModule,i10.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i11.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i17.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i17.ɵg,i17.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i11.ɵc(p0_0,p0_1),i17.ɵh(p1_0)];
              },[[2,i11.NgProbeToken],[2,i0.NgProbeToken],i17.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i11.BrowserModule,i11.BrowserModule,[[3,i11.BrowserModule]]),
          i0.ɵmpd(512,i13.BrowserAnimationsModule,i13.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i15.HttpModule,i15.HttpModule,([] as any[])),i0.ɵmpd(512,i16.ɵba,
              i16.ɵba,([] as any[])),i0.ɵmpd(512,i16.FormsModule,i16.FormsModule,([] as any[])),
          i0.ɵmpd(512,i16.ReactiveFormsModule,i16.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(1024,i17.ɵa,i17.ɵd,[[3,i17.Router]]),i0.ɵmpd(512,i17.UrlSerializer,
              i17.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i17.ChildrenOutletContexts,
              i17.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i17.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i10.LocationStrategy,i17.ɵc,[i10.PlatformLocation,
              [2,i10.APP_BASE_HREF],i17.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i10.Location,
              i10.Location,[i10.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i17.ROUTES,
              () => {
                return [[{path:'',component:i26.OrdersComponent},{path:'orders',redirectTo:'/',
                    pathMatch:'full'},{path:'products',component:i27.ProductsComponent},
                    {path:'customers',component:i28.CustomersComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i17.Router,i17.ɵe,[i0.ApplicationRef,i17.UrlSerializer,
              i17.ChildrenOutletContexts,i10.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i17.ROUTES,i17.ROUTER_CONFIGURATION,[2,i17.UrlHandlingStrategy],
              [2,i17.RouteReuseStrategy]]),i0.ɵmpd(512,i17.RouterModule,i17.RouterModule,
              [[2,i17.ɵa],[2,i17.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWFsaWtvdi9JZGVhUHJvamVjdHMvb3Ntcy9zcmMvbWFpbi9zcmMvYXBwL2Jvb3QubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tYWxpa292L0lkZWFQcm9qZWN0cy9vc21zL3NyYy9tYWluL3NyYy9hcHAvYm9vdC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
