/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../app/boot';
import * as i2 from '../../../../../app/app';
import * as i3 from './containers/orders/orders.component.ngfactory';
import * as i4 from './containers/products/products.component.ngfactory';
import * as i5 from './containers/customers/customers.component.ngfactory';
import * as i6 from './containers/poshta/poshta.component.ngfactory';
import * as i7 from './ui/autocomplete-list/autocomplete-list.ngfactory';
import * as i8 from './ui/popup/popup.ngfactory';
import * as i9 from './ui/noty/noty.ngfactory';
import * as i10 from './app.ngfactory';
import * as i11 from '@angular/common';
import * as i12 from '@angular/platform-browser';
import * as i13 from '@angular/animations/browser';
import * as i14 from '@angular/platform-browser/animations';
import * as i15 from '@angular/animations';
import * as i16 from '@angular/http';
import * as i17 from '@angular/forms';
import * as i18 from '@angular/router';
import * as i19 from '../../../../../app/store';
import * as i20 from '../../../../../app/services/api.service';
import * as i21 from '../../../../../app/services/store-helper.service';
import * as i22 from '../../../../../app/services/search.service';
import * as i23 from '../../../../../app/services/customers.service';
import * as i24 from '../../../../../app/services/noty.service';
import * as i25 from '../../../../../app/services/orders.service';
import * as i26 from '../../../../../app/services/products.service';
import * as i27 from '../../../../../app/services/poshta.service';
import * as i28 from '../../../../../app/containers/orders/orders.component';
import * as i29 from '../../../../../app/containers/products/products.component';
import * as i30 from '../../../../../app/containers/customers/customers.component';
import * as i31 from '../../../../../app/containers/poshta/poshta.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.App],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.OrdersComponentNgFactory,i4.ProductsComponentNgFactory,i5.CustomersComponentNgFactory,
              i6.PoshtaComponentNgFactory,i7.AutocompleteListNgFactory,i8.PopupComponentNgFactory,
              i9.NotyComponentNgFactory,i10.AppNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4352,i0.LOCALE_ID,'ru-RU',([] as any[])),i0.ɵmpd(4608,
          i11.NgLocalization,i11.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,
          i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i12.DomSanitizer,
              i12.ɵe,[i11.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i12.DomSanitizer]),
          i0.ɵmpd(4608,i12.HAMMER_GESTURE_CONFIG,i12.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i12.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i12.ɵDomEventsPlugin(p0_0),new i12.ɵKeyEventsPlugin(p1_0),
                new i12.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i11.DOCUMENT,i11.DOCUMENT,i11.DOCUMENT,i12.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i12.EventManager,i12.EventManager,[i12.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i12.ɵDomSharedStylesHost,i12.ɵDomSharedStylesHost,[i11.DOCUMENT]),
          i0.ɵmpd(4608,i12.ɵDomRendererFactory2,i12.ɵDomRendererFactory2,[i12.EventManager,
              i12.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i13.AnimationDriver,i14.ɵc,([] as any[])),
          i0.ɵmpd(5120,i13.ɵAnimationStyleNormalizer,i14.ɵd,([] as any[])),i0.ɵmpd(4608,
              i13.ɵAnimationEngine,i14.ɵb,[i13.AnimationDriver,i13.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i14.ɵe,[i12.ɵDomRendererFactory2,i13.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i12.ɵSharedStylesHost,(null as any),[i12.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i12.Meta,
              i12.Meta,[i11.DOCUMENT]),i0.ɵmpd(4608,i12.Title,i12.Title,[i11.DOCUMENT]),
          i0.ɵmpd(4608,i15.AnimationBuilder,i14.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
              i12.DOCUMENT]),i0.ɵmpd(4608,i16.BrowserXhr,i16.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i16.ResponseOptions,i16.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i16.XSRFStrategy,i16.ɵb,([] as any[])),i0.ɵmpd(4608,i16.XHRBackend,
              i16.XHRBackend,[i16.BrowserXhr,i16.ResponseOptions,i16.XSRFStrategy]),
          i0.ɵmpd(4608,i16.RequestOptions,i16.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i16.Http,i16.ɵc,[i16.XHRBackend,i16.RequestOptions]),i0.ɵmpd(4608,i17.ɵi,
              i17.ɵi,([] as any[])),i0.ɵmpd(4608,i17.FormBuilder,i17.FormBuilder,([] as any[])),
          i0.ɵmpd(5120,i18.ActivatedRoute,i18.ɵf,[i18.Router]),i0.ɵmpd(4608,i18.NoPreloading,
              i18.NoPreloading,([] as any[])),i0.ɵmpd(6144,i18.PreloadingStrategy,
              (null as any),[i18.NoPreloading]),i0.ɵmpd(135680,i18.RouterPreloader,
              i18.RouterPreloader,[i18.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i18.PreloadingStrategy]),i0.ɵmpd(4608,i18.PreloadAllModules,
              i18.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i18.ROUTER_INITIALIZER,
              i18.ɵi,[i18.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i18.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i19.Store,i19.Store,([] as any[])),
          i0.ɵmpd(4608,i20.ApiService,i20.ApiService,[i16.Http]),i0.ɵmpd(4608,i21.StoreHelper,
              i21.StoreHelper,[i19.Store]),i0.ɵmpd(4608,i22.SearchService,i22.SearchService,
              ([] as any[])),i0.ɵmpd(4608,i23.CustomerService,i23.CustomerService,
              [i20.ApiService,i21.StoreHelper,i22.SearchService]),i0.ɵmpd(4608,i24.NotyService,
              i24.NotyService,[i0.ComponentFactoryResolver]),i0.ɵmpd(4608,i25.OrderService,
              i25.OrderService,[i20.ApiService,i21.StoreHelper,i22.SearchService]),
          i0.ɵmpd(4608,i26.ProductService,i26.ProductService,[i20.ApiService,i21.StoreHelper,
              i22.SearchService]),i0.ɵmpd(4608,i27.PoshtaService,i27.PoshtaService,
              [i20.ApiService]),i0.ɵmpd(512,i11.CommonModule,i11.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i12.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i18.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i18.ɵg,i18.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i12.ɵc(p0_0,p0_1),i18.ɵh(p1_0)];
              },[[2,i12.NgProbeToken],[2,i0.NgProbeToken],i18.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i12.BrowserModule,i12.BrowserModule,[[3,i12.BrowserModule]]),
          i0.ɵmpd(512,i14.BrowserAnimationsModule,i14.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i16.HttpModule,i16.HttpModule,([] as any[])),i0.ɵmpd(512,i17.ɵba,
              i17.ɵba,([] as any[])),i0.ɵmpd(512,i17.FormsModule,i17.FormsModule,([] as any[])),
          i0.ɵmpd(512,i17.ReactiveFormsModule,i17.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(1024,i18.ɵa,i18.ɵd,[[3,i18.Router]]),i0.ɵmpd(512,i18.UrlSerializer,
              i18.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i18.ChildrenOutletContexts,
              i18.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i18.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i11.LocationStrategy,i18.ɵc,[i11.PlatformLocation,
              [2,i11.APP_BASE_HREF],i18.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i11.Location,
              i11.Location,[i11.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i18.ROUTES,
              () => {
                return [[{path:'',component:i28.OrdersComponent},{path:'products',
                    component:i29.ProductsComponent},{path:'customers',component:i30.CustomersComponent},
                    {path:'poshta',component:i31.PoshtaComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i18.Router,i18.ɵe,[i0.ApplicationRef,i18.UrlSerializer,
              i18.ChildrenOutletContexts,i11.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i18.ROUTES,i18.ROUTER_CONFIGURATION,[2,i18.UrlHandlingStrategy],
              [2,i18.RouteReuseStrategy]]),i0.ɵmpd(512,i18.RouterModule,i18.RouterModule,
              [[2,i18.ɵa],[2,i18.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWFsaWtvdi9JZGVhUHJvamVjdHMvb3Ntcy9zcmMvbWFpbi9zcmMvYXBwL2Jvb3QubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tYWxpa292L0lkZWFQcm9qZWN0cy9vc21zL3NyYy9tYWluL3NyYy9hcHAvYm9vdC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
