/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.pagination[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    justify-content: space-between;\r\n    align-items: flex-end;\r\n    margin: 20px 0;\r\n    font-size: 15px;\r\n}\r\n.pagination__right[_ngcontent-%COMP%] {\r\n    text-align: right;\r\n}\r\n.pagination__length[_ngcontent-%COMP%] {\r\n    margin: 0 0 10px;\r\n    font-size: 15px;\r\n}\r\n.pagination__selector[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    list-style: none;\r\n}\r\nli[_ngcontent-%COMP%] {\r\n    padding: 5px 10px;\r\n    user-select: none;\r\n    cursor: pointer;\r\n}\r\nli[_ngcontent-%COMP%]:hover, li.active[_ngcontent-%COMP%] {\r\n    background: #00bcd4;\r\n    color: #fff;\r\n}\r\nli.disabled[_ngcontent-%COMP%], li.disabled[_ngcontent-%COMP%]:hover, li.spread[_ngcontent-%COMP%], li.spread[_ngcontent-%COMP%]:hover {\r\n    background: transparent;\r\n    color: #999;\r\n    cursor: default;\r\n}\r\n@media only screen and (max-width: 500px) {\r\n    .pagination[_ngcontent-%COMP%] {\r\n        flex-wrap: wrap;\r\n    }\r\n\r\n    .pagination__info[_ngcontent-%COMP%] {\r\n        display: none;\r\n    }\r\n\r\n    .pagination__right[_ngcontent-%COMP%] {\r\n        margin-left: auto;\r\n    }\r\n\r\n    li.spread[_ngcontent-%COMP%] {\r\n        padding-left: 2px;\r\n        padding-right: 2px;\r\n    }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovT1NNUy9zcmMvbWFpbi9zcmMvYXBwL3VpL3BhZ2luYXRpb24vcGFnaW5hdGlvbi5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovT1NNUy9zcmMvbWFpbi9zcmMvYXBwL3VpL3BhZ2luYXRpb24vcGFnaW5hdGlvbi5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
